FIGDIR=../../bovy/nongauss-qso/tex

all: $(FIGDIR)/powerlawSF_constmean_u_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_g_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_r_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_i_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_u_wedge1_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_u_wedge0.25_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_u_wedge0.05_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_g_wedge0.5_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_g_wedge0.1_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_g_wedge0.01_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_r_wedge1_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_r_wedge0.25_skew.ps \
     $(FIGDIR)/powerlawSF_constmean_r_wedge0.05_skew.ps \
     $(FIGDIR)/rrlyrae_powerlawSF_constmean_u_skew.ps \
     $(FIGDIR)/rrlyrae_powerlawSF_constmean_g_skew.ps \
     $(FIGDIR)/rrlyrae_powerlawSF_constmean_r_skew.ps \
     $(FIGDIR)/rrlyrae_powerlawSF_constmean_i_skew.ps \
     $(FIGDIR)/star_powerlawSF_constmean_u_skew.ps \
     $(FIGDIR)/star_powerlawSF_constmean_g_skew.ps \
     $(FIGDIR)/star_powerlawSF_constmean_r_skew.ps \
     $(FIGDIR)/star_powerlawSF_constmean_i_skew.ps \


#Gaussian
../skew-wpv/powerlawSF_constmean_u_skew.sav: ../skew/powerlawSF_constmean_u_skew_1.sav
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/powerlawSF_constmean_u.sav -n 100 --saveevery=5 --split=250
../skew/powerlawSF_constmean_g_skew.sav: ../skew/powerlawSF_constmean_g_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/powerlawSF_constmean_g.sav -n 100 --saveevery=5 --split=250
../skew/powerlawSF_constmean_r_skew.sav: ../skew/powerlawSF_constmean_r_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/powerlawSF_constmean_r.sav -n 100 --saveevery=5 --split=250
../skew/powerlawSF_constmean_i_skew.sav: ../skew/powerlawSF_constmean_i_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/powerlawSF_constmean_i.sav -n 100 --saveevery=5 --split=250
$(FIGDIR)/powerlawSF_constmean_u_skew.ps: plotSkew.py ../skew/powerlawSF_constmean_u_skew.sav
	$(PYTHON) plotSkew.py ../skew-wpv/powerlawSF_constmean_u_skew.sav -o $@
$(FIGDIR)/powerlawSF_constmean_g_skew.ps: plotSkew.py ../skew/powerlawSF_constmean_g_skew.sav
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_g_skew.sav -o $@
$(FIGDIR)/powerlawSF_constmean_r_skew.ps: plotSkew.py ../skew/powerlawSF_constmean_r_skew.sav
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_r_skew.sav -o $@
$(FIGDIR)/powerlawSF_constmean_i_skew.ps: plotSkew.py ../skew/powerlawSF_constmean_i_skew.sav
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_i_skew.sav -o $@
#Dist
$(FIGDIR)/powerlawSF_constmean_u_skewdist.ps: plotSkewDist.py
	$(PYTHON) plotSkewDist.py ../skew/powerlawSF_constmean_u_skew.sav -o $@
$(FIGDIR)/powerlawSF_constmean_g_skewdist.ps: plotSkewDist.py
	$(PYTHON) plotSkewDist.py ../skew/powerlawSF_constmean_g_skew.sav -o $@

#RR Lyrae
../skew/rrlyrae_powerlawSF_constmean_u_skew.sav: ../skew/rrlyrae_powerlawSF_constmean_u_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/rrlyrae_powerlawSF_constmean_u.sav -n 100 --saveevery=5 --split=25
../skew/rrlyrae_powerlawSF_constmean_g_skew.sav: ../skew/rrlyrae_powerlawSF_constmean_g_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/rrlyrae_powerlawSF_constmean_g.sav -n 100 --saveevery=5 --split=25
../skew/rrlyrae_powerlawSF_constmean_r_skew.sav: ../skew/rrlyrae_powerlawSF_constmean_r_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/rrlyrae_powerlawSF_constmean_r.sav -n 100 --saveevery=5 --split=25
../skew/rrlyrae_powerlawSF_constmean_i_skew.sav: ../skew/rrlyrae_powerlawSF_constmean_i_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/rrlyrae_powerlawSF_constmean_i.sav -n 100 --saveevery=5 --split=25
$(FIGDIR)/rrlyrae_powerlawSF_constmean_u_skew.ps: plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_u_skew.sav
	$(PYTHON) plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_u_skew.sav -o $@
$(FIGDIR)/rrlyrae_powerlawSF_constmean_g_skew.ps: plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_g_skew.sav
	$(PYTHON) plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_g_skew.sav -o $@
$(FIGDIR)/rrlyrae_powerlawSF_constmean_r_skew.ps: plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_r_skew.sav
	$(PYTHON) plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_r_skew.sav -o $@
$(FIGDIR)/rrlyrae_powerlawSF_constmean_i_skew.ps: plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_i_skew.sav
	$(PYTHON) plotSkew.py ../skew/rrlyrae_powerlawSF_constmean_i_skew.sav -o $@
#Dist
$(FIGDIR)/rrlyrae_powerlawSF_constmean_g_skewdist.ps: plotSkewDist.py
	$(PYTHON) plotSkewDist.py ../skew/rrlyrae_powerlawSF_constmean_g_skew.sav -o $@

#Stars
../skew/star_powerlawSF_constmean_u_skew.sav: ../skew/star_powerlawSF_constmean_u_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/star_powerlawSF_constmean_u.sav -n 100 --saveevery=5 --split=250
../skew/star_powerlawSF_constmean_g_skew.sav: ../skew/star_powerlawSF_constmean_g_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/star_powerlawSF_constmean_g.sav -n 100 --saveevery=5 --split=250
../skew/star_powerlawSF_constmean_r_skew.sav: ../skew/star_powerlawSF_constmean_r_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/powerlawSF_constmean_r.sav -n 100 --saveevery=5 --split=250
../skew/star_powerlawSF_constmean_i_skew.sav: ../skew/star_powerlawSF_constmean_i_skew.sav_0
	$(PYTHON) gatherSavefiles.py $@ -b u -t powerlawSF --mean=const -f ../fits/star_powerlawSF_constmean_i.sav -n 100 --saveevery=5 --split=250
$(FIGDIR)/star_powerlawSF_constmean_u_skew.ps: plotSkew.py ../skew/star_powerlawSF_constmean_u_skew.sav
	$(PYTHON) plotSkew.py ../skew/star_powerlawSF_constmean_u_skew.sav -o $@
$(FIGDIR)/star_powerlawSF_constmean_g_skew.ps: plotSkew.py ../skew/star_powerlawSF_constmean_g_skew.sav
	$(PYTHON) plotSkew.py ../skew/star_powerlawSF_constmean_g_skew.sav -o $@
$(FIGDIR)/star_powerlawSF_constmean_r_skew.ps: plotSkew.py ../skew/star_powerlawSF_constmean_r_skew.sav
	$(PYTHON) plotSkew.py ../skew/star_powerlawSF_constmean_r_skew.sav -o $@
$(FIGDIR)/star_powerlawSF_constmean_i_skew.ps: plotSkew.py ../skew/star_powerlawSF_constmean_i_skew.sav
	$(PYTHON) plotSkew.py ../skew/star_powerlawSF_constmean_i_skew.sav -o $@
#Dist
$(FIGDIR)/star_powerlawSF_constmean_g_skewdist.ps: plotSkewDist.py
	$(PYTHON) plotSkewDist.py ../skew/star_powerlawSF_constmean_g_skew.sav -o $@

#Skews u
$(FIGDIR)/powerlawSF_constmean_u_wedge1_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_u_skew_wedge1.sav -o $@
$(FIGDIR)/powerlawSF_constmean_u_wedge0.25_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_u_skew_wedge0.25.sav -o $@
$(FIGDIR)/powerlawSF_constmean_u_wedge0.05_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_u_skew_wedge0.05.sav -o $@

#Skews u
$(FIGDIR)/powerlawSF_constmean_g_wedge0.5_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_g_skew_wedge0.5.sav -o $@
$(FIGDIR)/powerlawSF_constmean_g_wedge0.1_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_g_skew_wedge0.1.sav -o $@
$(FIGDIR)/powerlawSF_constmean_g_wedge0.01_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_g_skew_wedge0.01.sav -o $@

#Skews r
$(FIGDIR)/powerlawSF_constmean_r_wedge1_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_r_skew_wedge1.sav -o $@
$(FIGDIR)/powerlawSF_constmean_r_wedge0.25_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_r_skew_wedge0.25.sav -o $@
$(FIGDIR)/powerlawSF_constmean_r_wedge0.05_skew.ps: plotSkew.py
	$(PYTHON) plotSkew.py ../skew/powerlawSF_constmean_r_skew_wedge0.05.sav -o $@
